/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsGetById } from "../../funcs/petsGetById.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetPetByIdRequest$inboundSchema,
};

export const tool$petsGetById: ToolDefinition<typeof args> = {
  name: "pets-get-by-id",
  description: `Find pet by ID

Returns a single pet`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petsGetById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
